# https://wiki.hypr.land/Configuring/Keywords/#executing

exec-once = waybar # System bar
exec-once = hypridle # Idle daemon
exec-once = hyprpaper # Wallpaper daemon
exec-once = /opt/TgWsProxy_linux_amd64
