--  Neovim Settings
require("core.mappings")
require("core.settings")
require("core.theme")

-- Plugin Setting
require("plugins.autocomplete")
require("plugins.dashboard")
require("plugins.db")
require("plugins.discord")
require("plugins.dotnet")
require("plugins.git")
require("plugins.imageviewer")
require("plugins.lsp")
require("plugins.markdown")
require("plugins.mason")
require("plugins.neotree")
require("plugins.tabs")
require("plugins.telescope")
require("plugins.treesitter")
